# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f5254f2798cbcfcd5dd9ae2db0569a993d9768f0d0cc5019b24f3818646bbb3e73fbac74b203100acd28278292696c59f9c8b22ad64fb28eb8184f0116dddb1
  smtp_setting:
    domain:  <%= ENV["ONECLICK_SMTP_DOMAIN"] %>
    user_name:  <%= ENV["ONECLICK_SMTP_USERNAME"] %>
    password:  <%= ENV["ONECLICK_SMTP_PASSWORD"] %>

test:
  secret_key_base: 8686a96705ed4052ff3f3e25203a6324e158240c8bc2cad3ebf63390c0a7f0f14ef96206846c3f42e16f069c5db03c801e334ba49a6dbc263b2a5f59b309110c
  smtp_setting:
    domain:  <%= ENV["ONECLICK_SMTP_DOMAIN"] %>
    user_name:  <%= ENV["ONECLICK_SMTP_USERNAME"] %>
    password:  <%= ENV["ONECLICK_SMTP_PASSWORD"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  smtp_setting:
    domain:  <%= ENV["ONECLICK_SMTP_DOMAIN"] %>
    user_name:  <%= ENV["ONECLICK_SMTP_USERNAME"] %>
    password:  <%= ENV["ONECLICK_SMTP_PASSWORD"] %>
